const ActionTypes = {
  IS_SIGN_LODER: "IS_SIGN_LODER",
  IS_REGISTER_ERROR:"IS_REGISTER_ERROR",
  PARKING_LIST:"PARKING_LIST",
  PARKING_ID:"PARKING_ID",
  SLOTS_:"SLOTS_",
  SELECTED_DATA:"SELECTED_DATA",
  MY_SLOTS:"MY_SLOTS",
  AREA_NAME:"AREA_NAME"
  
}

export default ActionTypes